### ISSUE TITLE
Please improve documentation

### ISSUE THREAD

**Issue by JJ** [hythm7/Pakku-Spec#1]
It's really difficult to know, by just looking at this README, what the distribution is about. Just a link to the Pakku repo or web site would help, for instance, but additionally, some simple use case would also be helpful.

**Comment by hythm7** [comment]
Hi, I just updated the `description` section, Please let me know if the purpose of the distribution makes sense now or still not clear.

**Comment by JJ** [comment]
Much clearer now, although you might want to say right there that Pakku is a package manager :-)

**Comment by hythm7** [comment]
Done. Thanks for suggestions :)

**Comment by JJ** [comment]
Thanks!
